version: "3.1"

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432

  nginx:
    image: nginx
    container_name: wishlify-nginx
    volumes:
      - ./nginx:/etc/nginx/templates
    ports:
      - 80:80
